version: "3"
services:
  node:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - "testnet:/root/.bitcore/data/testnet3"
    command: bash -c "pm2 start bitcored && pm2 logs bitcored"
    stdin_open: true
    tty: true

volumes:
  testnet:
